### ISSUE TITLE
Problem merging persons with training progress

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1136]
Try merging https://amy.software-carpentry.org/workshops/person/12051/ and https://amy.software-carpentry.org/workshops/person/12839/  

![image](https://cloud.githubusercontent.com/assets/829690/22038955/3cb3f0a2-dccb-11e6-869e-ebf84bc298a2.png)

**Comment by chrismedrela** [comment]
@maneesha Please use "combine" for "Training progresses". Let me know if this helped.

**Comment by pbanaszkiewicz** [comment]
@maneesha @chrismedrela I'm almost sure that this was fixed in v1.10 - it works on my development server and production database.

**Comment by maneesha** [comment]
As of now, I still get this error.  
"Training progress" is not an option in all the fields you can merge.

**Comment by pbanaszkiewicz** [comment]
@maneesha I'm pretty sure this will be fixed when we release v1.10.

**Comment by chrismedrela** [comment]
@maneesha, yes that was fixed in #1118. I'm closing it as it's a duplicate of #1117.
